// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQnyNpKF2vCGHdaLC3RGuqzOk6QFaGgyw',
    appId: '1:230960917366:web:d5f9280689e904d9eb2857',
    messagingSenderId: '230960917366',
    projectId: 'freshsoc-fdef2',
    authDomain: 'freshsoc-fdef2.firebaseapp.com',
    storageBucket: 'freshsoc-fdef2.appspot.com',
    measurementId: 'G-M6185QG96Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEf6PHCJXhCMbTtJpqy7kDzEpI9IwH5i4',
    appId: '1:230960917366:android:74c8d8b286aa0a7aeb2857',
    messagingSenderId: '230960917366',
    projectId: 'freshsoc-fdef2',
    storageBucket: 'freshsoc-fdef2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByBs-txdVTJtCWDxAKGu05exKLjcwMF_4',
    appId: '1:230960917366:ios:2e743c699b3630d3eb2857',
    messagingSenderId: '230960917366',
    projectId: 'freshsoc-fdef2',
    storageBucket: 'freshsoc-fdef2.appspot.com',
    iosClientId: '230960917366-ms2cssam87ifl31mgkk3rcqcetuk9bic.apps.googleusercontent.com',
    iosBundleId: 'com.example.freshsoc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByBs-txdVTJtCWDxAKGu05exKLjcwMF_4',
    appId: '1:230960917366:ios:2e743c699b3630d3eb2857',
    messagingSenderId: '230960917366',
    projectId: 'freshsoc-fdef2',
    storageBucket: 'freshsoc-fdef2.appspot.com',
    iosClientId: '230960917366-ms2cssam87ifl31mgkk3rcqcetuk9bic.apps.googleusercontent.com',
    iosBundleId: 'com.example.freshsoc',
  );
}
